name: Setup Standalone pnpm
author: Alfi Maulana
description: Set up standalone pnpm on the runner
branding:
  icon: package
  color: orange
inputs:
  version:
    description: The version or tag of pnpm to install.
  version-file:
    description: A file specifying the version of pnpm to install. Supports package.json with a packageManager field.
outputs:
  version:
    description: The version of pnpm that was installed.
runs:
  using: node24
  main: dist/main.js
