name: Setup pnpm Action
author: Alfi Maulana
description: Set up pnpm with a specified version
branding:
  icon: chevrons-right
  color: black
inputs:
  path:
    description: Path of the directory to create
    required: true
runs:
  using: node20
  main: dist/main.bundle.mjs
