name: Setup Standalone pnpm
author: Alfi Maulana
description: Set up standalone pnpm with a specified version
branding:
  icon: package
  color: orange
inputs:
  version:
    description: The version or tag of pnpm to set up.
    default: latest
outputs:
  version:
    description: Resolved version of pnpm that was installed.
runs:
  using: node24
  main: dist/main.js
