name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Setup Lefthook
        uses: threeal/setup-lefthook-action@v1.0.0

      - name: Setup pnpm
        uses: ./
        with:
          version-file: package.json

      - name: Check pre-commit hook
        run: lefthook run pre-commit --all-files

      - name: Test
        run: pnpm vitest run

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - windows-11-arm
          - macos-15
          - macos-15-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
        with:
          path: setup-pnpm-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Setup pnpm
        id: setup-pnpm
        if: matrix.os != 'macos-15-intel'
        uses: ./setup-pnpm-action

      - name: Verify pnpm version
        if: matrix.os != 'macos-15-intel'
        shell: bash
        run: |
          version="$(pnpm --version)"
          echo "$version"
          test "$version" != "10.34.0"
          test "$version" = "${{ steps.setup-pnpm.outputs.version }}"

      - name: Setup pnpm with version input
        id: setup-pnpm-version
        uses: ./setup-pnpm-action
        with:
          version: 10.34.0

      - name: Verify pnpm version
        # TODO: pnpm v10 and below verification keeps failing on Windows arm64 runners
        if: matrix.os != 'windows-11-arm'
        shell: bash
        run: |
          version="$(pnpm --version)"
          echo "$version"
          test "$version" = "10.34.0"
          test "$version" = "${{ steps.setup-pnpm-version.outputs.version }}"

      - name: Write package.json
        shell: bash
        run: |
          mkdir project
          echo '{"packageManager":"pnpm@9.15.0"}' > project/package.json

      - name: Setup pnpm with version-file input
        id: setup-pnpm-version-file
        uses: ./setup-pnpm-action
        with:
          version-file: project/package.json

      - name: Verify pnpm version
        # TODO: pnpm v10 and below verification keeps failing on Windows arm64 runners
        if: matrix.os != 'windows-11-arm'
        shell: bash
        run: |
          version="$(pnpm --version)"
          echo "$version"
          test "$version" = "9.15.0"
          test "$version" = "${{ steps.setup-pnpm-version-file.outputs.version }}"

      - name: Setup pnpm from cache
        id: setup-pnpm-cached
        if: matrix.os != 'macos-15-intel'
        uses: ./setup-pnpm-action
        env:
          PATH: "" # forces cache usage by making curl unavailable

      - name: Verify pnpm version
        if: matrix.os != 'macos-15-intel'
        shell: bash
        run: |
          version="$(pnpm --version)"
          echo "$version"
          test "$version" != "10.34.0"
          test "$version" = "${{ steps.setup-pnpm-cached.outputs.version }}"
