name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.2.2
        with:
          path: setup-pnpm-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Setup pnpm
        uses: ./setup-pnpm-action

      - name: Check pnpm
        run: pnpm --version

      - name: Setup pnpm With a Specified Version
        uses: ./setup-pnpm-action
        with:
          version: 9.15.5

      - name: Check pnpm
        run: pnpm --version
