name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.2.2
        with:
          path: setup-pnpm-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Setup pnpm
        uses: ./setup-pnpm-action

      - name: Check pnpm
        run: pnpm --version
